# spring.application.name=serverseplag

# # configuracao de porta
# server.port=8080


# # configuracao de pgsql
# spring.datasource.url=jdbc:postgresql://localhost:5432/serverseplag
# spring.datasource.username=postgres
# spring.datasource.password=1308
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# # Configuracao JPA
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# minio:
#   endpoint: http://localhost:9000  # URL do MinIO
#   access-key: minioadmin            # Usuário padrão
#   secret-key: minioadmin            # Senha padrão
#   bucket: albuns-capas              # Nome do bucket para as capas
#   presigned-expiry: 30              # Expiração da URL em minutos

# spring:
#   servlet:
#     multipart:
#       max-file-size: 10MB           # Tamanho máximo do arquivo
#       max-request-size: 10MB

spring.application.name=serverseplag

# configuracao de porta
server.port=8080

# configuracao de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/serverseplag
spring.datasource.username=postgres
spring.datasource.password=1308
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes do MinIO (formato properties)
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=albuns-capas
minio.presigned-expiry=30

# Configuracoes de upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# API para - jwt
api.secret.token.secret=${JWT_SECRET:default_secret_key}

# Configuração para debug do Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.com.seplag.serverseplag=DEBUG